version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/voting.db
      - KEYS_PATH=/app/data/election_keys.json
    restart: unless-stopped

volumes:
  backend_data: 